# Generated by Django 2.1.5 on 2019-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0002_auto_20190130_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='extracted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
