# Generated by Django 2.1.5 on 2019-01-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0005_auto_20190130_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='district_id',
            field=models.IntegerField(default=0),
        ),
    ]
