# Generated by Django 2.1.5 on 2019-01-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0006_auto_20190130_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policestation',
            name='station_id',
        ),
        migrations.AlterField(
            model_name='policestation',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
