# Generated by Django 2.1.5 on 2019-01-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0007_auto_20190130_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policestation',
            name='last_fir_id',
            field=models.CharField(default='', max_length=13),
        ),
    ]
