# Generated by Django 2.1.5 on 2019-02-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0009_fir_psdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fir',
            name='act',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='address',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='all_charge',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='final_charge',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fir',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='fir',
            name='psdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='section',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='wrong_address',
            field=models.BooleanField(null=True),
        ),
    ]
