# Generated by Django 2.1.5 on 2019-02-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataCollection', '0010_auto_20190204_1942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fir',
            name='psdate',
        ),
        migrations.AlterField(
            model_name='fir',
            name='act',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='fir',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='fir',
            name='all_charge',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='fir',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='fir',
            name='final_charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='fir',
            name='section',
            field=models.CharField(default='', max_length=50),
        ),
    ]
